[package]
name = "day-05"
version = "0.1.0"
edition = "2021"

[features]
# Evaluate the input as per part one's specification.
part1 = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
